export default [
  {
    type: "constructor",
    stateMutability: "nonpayable",
    inputs: [
      {
        type: "address",
        name: "bentoBox_",
        internalType: "contract IBentoBoxV1",
      },
      {
        type: "address",
        name: "magicInternetMoney_",
        internalType: "contract IERC20",
      },
    ],
  },
  {
    type: "event",
    name: "LogAccrue",
    inputs: [
      {
        type: "uint128",
        name: "accruedAmount",
        internalType: "uint128",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LogAddCollateral",
    inputs: [
      {
        type: "address",
        name: "from",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "to",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "share",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LogBorrow",
    inputs: [
      {
        type: "address",
        name: "from",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "to",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "amount",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "part",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LogExchangeRate",
    inputs: [
      {
        type: "uint256",
        name: "rate",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LogFeeTo",
    inputs: [
      {
        type: "address",
        name: "newFeeTo",
        internalType: "address",
        indexed: true,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LogRemoveCollateral",
    inputs: [
      {
        type: "address",
        name: "from",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "to",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "share",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LogRepay",
    inputs: [
      {
        type: "address",
        name: "from",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "to",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "amount",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "part",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LogWithdrawFees",
    inputs: [
      {
        type: "address",
        name: "feeTo",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "feesEarnedFraction",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        type: "address",
        name: "previousOwner",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "newOwner",
        internalType: "address",
        indexed: true,
      },
    ],
    anonymous: false,
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "BORROW_OPENING_FEE",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "COLLATERIZATION_RATE",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "LIQUIDATION_MULTIPLIER",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "accrue",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "uint64", name: "lastAccrued", internalType: "uint64" },
      { type: "uint128", name: "feesEarned", internalType: "uint128" },
      {
        type: "uint64",
        name: "INTEREST_PER_SECOND",
        internalType: "uint64",
      },
    ],
    name: "accrueInfo",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "addCollateral",
    inputs: [
      { type: "address", name: "to", internalType: "address" },
      { type: "bool", name: "skim", internalType: "bool" },
      { type: "uint256", name: "share", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "address", name: "", internalType: "contract IBentoBoxV1" },
    ],
    name: "bentoBox",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [
      { type: "uint256", name: "part", internalType: "uint256" },
      { type: "uint256", name: "share", internalType: "uint256" },
    ],
    name: "borrow",
    inputs: [
      { type: "address", name: "to", internalType: "address" },
      { type: "uint256", name: "amount", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "claimOwnership",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "contract IERC20" }],
    name: "collateral",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "payable",
    outputs: [
      { type: "uint256", name: "value1", internalType: "uint256" },
      { type: "uint256", name: "value2", internalType: "uint256" },
    ],
    name: "cook",
    inputs: [
      { type: "uint8[]", name: "actions", internalType: "uint8[]" },
      { type: "uint256[]", name: "values", internalType: "uint256[]" },
      { type: "bytes[]", name: "datas", internalType: "bytes[]" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "exchangeRate",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "feeTo",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "payable",
    outputs: [],
    name: "init",
    inputs: [{ type: "bytes", name: "data", internalType: "bytes" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "liquidate",
    inputs: [
      { type: "address[]", name: "users", internalType: "address[]" },
      {
        type: "uint256[]",
        name: "maxBorrowParts",
        internalType: "uint256[]",
      },
      { type: "address", name: "to", internalType: "address" },
      {
        type: "address",
        name: "swapper",
        internalType: "contract ISwapper",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "contract IERC20" }],
    name: "magicInternetMoney",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "address",
        name: "",
        internalType: "contract CauldronV2Multichain",
      },
    ],
    name: "masterContract",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "contract IOracle" }],
    name: "oracle",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bytes", name: "", internalType: "bytes" }],
    name: "oracleData",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "owner",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "pendingOwner",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "reduceSupply",
    inputs: [{ type: "uint256", name: "amount", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "removeCollateral",
    inputs: [
      { type: "address", name: "to", internalType: "address" },
      { type: "uint256", name: "share", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "uint256", name: "amount", internalType: "uint256" }],
    name: "repay",
    inputs: [
      { type: "address", name: "to", internalType: "address" },
      { type: "bool", name: "skim", internalType: "bool" },
      { type: "uint256", name: "part", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setFeeTo",
    inputs: [{ type: "address", name: "newFeeTo", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "uint128", name: "elastic", internalType: "uint128" },
      { type: "uint128", name: "base", internalType: "uint128" },
    ],
    name: "totalBorrow",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "totalCollateralShare",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "transferOwnership",
    inputs: [
      { type: "address", name: "newOwner", internalType: "address" },
      { type: "bool", name: "direct", internalType: "bool" },
      { type: "bool", name: "renounce", internalType: "bool" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [
      { type: "bool", name: "updated", internalType: "bool" },
      { type: "uint256", name: "rate", internalType: "uint256" },
    ],
    name: "updateExchangeRate",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "userBorrowPart",
    inputs: [{ type: "address", name: "", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "userCollateralShare",
    inputs: [{ type: "address", name: "", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "withdrawFees",
    inputs: [],
  },
];
