export default [
  {
    type: "constructor",
    stateMutability: "nonpayable",
    inputs: [
      { type: "uint256", name: "_poolId", internalType: "uint256" },
      { type: "address", name: "_router", internalType: "address" },
      { type: "address", name: "_token", internalType: "address" },
      { type: "uint256", name: "_sharedDecimals", internalType: "uint256" },
      { type: "uint256", name: "_localDecimals", internalType: "uint256" },
      { type: "address", name: "_feeLibrary", internalType: "address" },
      { type: "string", name: "_name", internalType: "string" },
      { type: "string", name: "_symbol", internalType: "string" },
    ],
  },
  {
    type: "event",
    name: "Approval",
    inputs: [
      {
        type: "address",
        name: "owner",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "spender",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "value",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Burn",
    inputs: [
      {
        type: "address",
        name: "from",
        internalType: "address",
        indexed: false,
      },
      {
        type: "uint256",
        name: "amountLP",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "amountSD",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChainPathUpdate",
    inputs: [
      {
        type: "uint16",
        name: "dstChainId",
        internalType: "uint16",
        indexed: false,
      },
      {
        type: "uint256",
        name: "dstPoolId",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "weight",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CreditChainPath",
    inputs: [
      {
        type: "uint16",
        name: "chainId",
        internalType: "uint16",
        indexed: false,
      },
      {
        type: "uint256",
        name: "srcPoolId",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "amountSD",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "idealBalance",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DeltaParamUpdated",
    inputs: [
      { type: "bool", name: "batched", internalType: "bool", indexed: false },
      {
        type: "uint256",
        name: "swapDeltaBP",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "lpDeltaBP",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "bool",
        name: "defaultSwapMode",
        internalType: "bool",
        indexed: false,
      },
      {
        type: "bool",
        name: "defaultLPMode",
        internalType: "bool",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FeeLibraryUpdated",
    inputs: [
      {
        type: "address",
        name: "feeLibraryAddr",
        internalType: "address",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FeesUpdated",
    inputs: [
      {
        type: "uint256",
        name: "mintFeeBP",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "InstantRedeemLocal",
    inputs: [
      {
        type: "address",
        name: "from",
        internalType: "address",
        indexed: false,
      },
      {
        type: "uint256",
        name: "amountLP",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "amountSD",
        internalType: "uint256",
        indexed: false,
      },
      { type: "address", name: "to", internalType: "address", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Mint",
    inputs: [
      { type: "address", name: "to", internalType: "address", indexed: false },
      {
        type: "uint256",
        name: "amountLP",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "amountSD",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "mintFeeAmountSD",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RedeemLocal",
    inputs: [
      {
        type: "address",
        name: "from",
        internalType: "address",
        indexed: false,
      },
      {
        type: "uint256",
        name: "amountLP",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "amountSD",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint16",
        name: "chainId",
        internalType: "uint16",
        indexed: false,
      },
      {
        type: "uint256",
        name: "dstPoolId",
        internalType: "uint256",
        indexed: false,
      },
      { type: "bytes", name: "to", internalType: "bytes", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RedeemLocalCallback",
    inputs: [
      { type: "address", name: "_to", internalType: "address", indexed: false },
      {
        type: "uint256",
        name: "_amountSD",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "_amountToMintSD",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RedeemRemote",
    inputs: [
      {
        type: "uint16",
        name: "chainId",
        internalType: "uint16",
        indexed: false,
      },
      {
        type: "uint256",
        name: "dstPoolId",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "address",
        name: "from",
        internalType: "address",
        indexed: false,
      },
      {
        type: "uint256",
        name: "amountLP",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "amountSD",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SendCredits",
    inputs: [
      {
        type: "uint16",
        name: "dstChainId",
        internalType: "uint16",
        indexed: false,
      },
      {
        type: "uint256",
        name: "dstPoolId",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "credits",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "idealBalance",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "StopSwapUpdated",
    inputs: [
      { type: "bool", name: "swapStop", internalType: "bool", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Swap",
    inputs: [
      {
        type: "uint16",
        name: "chainId",
        internalType: "uint16",
        indexed: false,
      },
      {
        type: "uint256",
        name: "dstPoolId",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "address",
        name: "from",
        internalType: "address",
        indexed: false,
      },
      {
        type: "uint256",
        name: "amountSD",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "eqReward",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "eqFee",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "protocolFee",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "lpFee",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SwapRemote",
    inputs: [
      { type: "address", name: "to", internalType: "address", indexed: false },
      {
        type: "uint256",
        name: "amountSD",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "protocolFee",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "dstFee",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Transfer",
    inputs: [
      { type: "address", name: "from", internalType: "address", indexed: true },
      { type: "address", name: "to", internalType: "address", indexed: true },
      {
        type: "uint256",
        name: "value",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WithdrawMintFeeBalance",
    inputs: [
      { type: "address", name: "to", internalType: "address", indexed: false },
      {
        type: "uint256",
        name: "amountSD",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WithdrawProtocolFeeBalance",
    inputs: [
      { type: "address", name: "to", internalType: "address", indexed: false },
      {
        type: "uint256",
        name: "amountSD",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WithdrawRemote",
    inputs: [
      {
        type: "uint16",
        name: "srcChainId",
        internalType: "uint16",
        indexed: false,
      },
      {
        type: "uint256",
        name: "srcPoolId",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "swapAmount",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "mintAmount",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "BP_DENOMINATOR",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bytes32", name: "", internalType: "bytes32" }],
    name: "DOMAIN_SEPARATOR",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bytes32", name: "", internalType: "bytes32" }],
    name: "PERMIT_TYPEHASH",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "activateChainPath",
    inputs: [
      { type: "uint16", name: "_dstChainId", internalType: "uint16" },
      { type: "uint256", name: "_dstPoolId", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "allowance",
    inputs: [
      { type: "address", name: "", internalType: "address" },
      { type: "address", name: "", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "amountLPtoLD",
    inputs: [{ type: "uint256", name: "_amountLP", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "approve",
    inputs: [
      { type: "address", name: "spender", internalType: "address" },
      { type: "uint256", name: "value", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "balanceOf",
    inputs: [{ type: "address", name: "", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "batched",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "callDelta",
    inputs: [{ type: "bool", name: "_fullMode", internalType: "bool" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "chainPathIndexLookup",
    inputs: [
      { type: "uint16", name: "", internalType: "uint16" },
      { type: "uint256", name: "", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "bool", name: "ready", internalType: "bool" },
      { type: "uint16", name: "dstChainId", internalType: "uint16" },
      { type: "uint256", name: "dstPoolId", internalType: "uint256" },
      { type: "uint256", name: "weight", internalType: "uint256" },
      { type: "uint256", name: "balance", internalType: "uint256" },
      { type: "uint256", name: "lkb", internalType: "uint256" },
      { type: "uint256", name: "credits", internalType: "uint256" },
      { type: "uint256", name: "idealBalance", internalType: "uint256" },
    ],
    name: "chainPaths",
    inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "convertRate",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "createChainPath",
    inputs: [
      { type: "uint16", name: "_dstChainId", internalType: "uint16" },
      { type: "uint256", name: "_dstPoolId", internalType: "uint256" },
      { type: "uint256", name: "_weight", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "creditChainPath",
    inputs: [
      { type: "uint16", name: "_dstChainId", internalType: "uint16" },
      { type: "uint256", name: "_dstPoolId", internalType: "uint256" },
      {
        type: "tuple",
        name: "_c",
        internalType: "struct Pool.CreditObj",
        components: [
          { type: "uint256", name: "credits", internalType: "uint256" },
          { type: "uint256", name: "idealBalance", internalType: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "decimals",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "decreaseAllowance",
    inputs: [
      { type: "address", name: "spender", internalType: "address" },
      { type: "uint256", name: "subtractedValue", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "defaultLPMode",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "defaultSwapMode",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "deltaCredit",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "eqFeePool",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "feeLibrary",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "tuple",
        name: "",
        internalType: "struct Pool.ChainPath",
        components: [
          { type: "bool", name: "ready", internalType: "bool" },
          { type: "uint16", name: "dstChainId", internalType: "uint16" },
          { type: "uint256", name: "dstPoolId", internalType: "uint256" },
          { type: "uint256", name: "weight", internalType: "uint256" },
          { type: "uint256", name: "balance", internalType: "uint256" },
          { type: "uint256", name: "lkb", internalType: "uint256" },
          { type: "uint256", name: "credits", internalType: "uint256" },
          { type: "uint256", name: "idealBalance", internalType: "uint256" },
        ],
      },
    ],
    name: "getChainPath",
    inputs: [
      { type: "uint16", name: "_dstChainId", internalType: "uint16" },
      { type: "uint256", name: "_dstPoolId", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "getChainPathsLength",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "increaseAllowance",
    inputs: [
      { type: "address", name: "spender", internalType: "address" },
      { type: "uint256", name: "addedValue", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "uint256", name: "amountSD", internalType: "uint256" }],
    name: "instantRedeemLocal",
    inputs: [
      { type: "address", name: "_from", internalType: "address" },
      { type: "uint256", name: "_amountLP", internalType: "uint256" },
      { type: "address", name: "_to", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "localDecimals",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "lpDeltaBP",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "mint",
    inputs: [
      { type: "address", name: "_to", internalType: "address" },
      { type: "uint256", name: "_amountLD", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "mintFeeBP",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "mintFeeBalance",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "string", name: "", internalType: "string" }],
    name: "name",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "nonces",
    inputs: [{ type: "address", name: "", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "permit",
    inputs: [
      { type: "address", name: "owner", internalType: "address" },
      { type: "address", name: "spender", internalType: "address" },
      { type: "uint256", name: "value", internalType: "uint256" },
      { type: "uint256", name: "deadline", internalType: "uint256" },
      { type: "uint8", name: "v", internalType: "uint8" },
      { type: "bytes32", name: "r", internalType: "bytes32" },
      { type: "bytes32", name: "s", internalType: "bytes32" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "poolId",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "protocolFeeBalance",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "uint256", name: "amountSD", internalType: "uint256" }],
    name: "redeemLocal",
    inputs: [
      { type: "address", name: "_from", internalType: "address" },
      { type: "uint256", name: "_amountLP", internalType: "uint256" },
      { type: "uint16", name: "_dstChainId", internalType: "uint16" },
      { type: "uint256", name: "_dstPoolId", internalType: "uint256" },
      { type: "bytes", name: "_to", internalType: "bytes" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "redeemLocalCallback",
    inputs: [
      { type: "uint16", name: "_srcChainId", internalType: "uint16" },
      { type: "uint256", name: "_srcPoolId", internalType: "uint256" },
      { type: "address", name: "_to", internalType: "address" },
      { type: "uint256", name: "_amountSD", internalType: "uint256" },
      { type: "uint256", name: "_amountToMintSD", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [
      { type: "uint256", name: "swapAmount", internalType: "uint256" },
      { type: "uint256", name: "mintAmount", internalType: "uint256" },
    ],
    name: "redeemLocalCheckOnRemote",
    inputs: [
      { type: "uint16", name: "_srcChainId", internalType: "uint16" },
      { type: "uint256", name: "_srcPoolId", internalType: "uint256" },
      { type: "uint256", name: "_amountSD", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "redeemRemote",
    inputs: [
      { type: "uint16", name: "_dstChainId", internalType: "uint16" },
      { type: "uint256", name: "_dstPoolId", internalType: "uint256" },
      { type: "address", name: "_from", internalType: "address" },
      { type: "uint256", name: "_amountLP", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "router",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [
      {
        type: "tuple",
        name: "c",
        internalType: "struct Pool.CreditObj",
        components: [
          { type: "uint256", name: "credits", internalType: "uint256" },
          { type: "uint256", name: "idealBalance", internalType: "uint256" },
        ],
      },
    ],
    name: "sendCredits",
    inputs: [
      { type: "uint16", name: "_dstChainId", internalType: "uint16" },
      { type: "uint256", name: "_dstPoolId", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setDeltaParam",
    inputs: [
      { type: "bool", name: "_batched", internalType: "bool" },
      { type: "uint256", name: "_swapDeltaBP", internalType: "uint256" },
      { type: "uint256", name: "_lpDeltaBP", internalType: "uint256" },
      { type: "bool", name: "_defaultSwapMode", internalType: "bool" },
      { type: "bool", name: "_defaultLPMode", internalType: "bool" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setFee",
    inputs: [{ type: "uint256", name: "_mintFeeBP", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setFeeLibrary",
    inputs: [
      { type: "address", name: "_feeLibraryAddr", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setSwapStop",
    inputs: [{ type: "bool", name: "_swapStop", internalType: "bool" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setWeightForChainPath",
    inputs: [
      { type: "uint16", name: "_dstChainId", internalType: "uint16" },
      { type: "uint256", name: "_dstPoolId", internalType: "uint256" },
      { type: "uint16", name: "_weight", internalType: "uint16" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "sharedDecimals",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "stopSwap",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [
      {
        type: "tuple",
        name: "",
        internalType: "struct Pool.SwapObj",
        components: [
          { type: "uint256", name: "amount", internalType: "uint256" },
          { type: "uint256", name: "eqFee", internalType: "uint256" },
          { type: "uint256", name: "eqReward", internalType: "uint256" },
          { type: "uint256", name: "lpFee", internalType: "uint256" },
          { type: "uint256", name: "protocolFee", internalType: "uint256" },
          { type: "uint256", name: "lkbRemove", internalType: "uint256" },
        ],
      },
    ],
    name: "swap",
    inputs: [
      { type: "uint16", name: "_dstChainId", internalType: "uint16" },
      { type: "uint256", name: "_dstPoolId", internalType: "uint256" },
      { type: "address", name: "_from", internalType: "address" },
      { type: "uint256", name: "_amountLD", internalType: "uint256" },
      { type: "uint256", name: "_minAmountLD", internalType: "uint256" },
      { type: "bool", name: "newLiquidity", internalType: "bool" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "swapDeltaBP",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "uint256", name: "amountLD", internalType: "uint256" }],
    name: "swapRemote",
    inputs: [
      { type: "uint16", name: "_srcChainId", internalType: "uint16" },
      { type: "uint256", name: "_srcPoolId", internalType: "uint256" },
      { type: "address", name: "_to", internalType: "address" },
      {
        type: "tuple",
        name: "_s",
        internalType: "struct Pool.SwapObj",
        components: [
          { type: "uint256", name: "amount", internalType: "uint256" },
          { type: "uint256", name: "eqFee", internalType: "uint256" },
          { type: "uint256", name: "eqReward", internalType: "uint256" },
          { type: "uint256", name: "lpFee", internalType: "uint256" },
          { type: "uint256", name: "protocolFee", internalType: "uint256" },
          { type: "uint256", name: "lkbRemove", internalType: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "string", name: "", internalType: "string" }],
    name: "symbol",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "token",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "totalLiquidity",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "totalSupply",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "totalWeight",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "transfer",
    inputs: [
      { type: "address", name: "to", internalType: "address" },
      { type: "uint256", name: "value", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "transferFrom",
    inputs: [
      { type: "address", name: "from", internalType: "address" },
      { type: "address", name: "to", internalType: "address" },
      { type: "uint256", name: "value", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "withdrawMintFeeBalance",
    inputs: [{ type: "address", name: "_to", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "withdrawProtocolFeeBalance",
    inputs: [{ type: "address", name: "_to", internalType: "address" }],
  },
];
