export default [
  {
    name: "3PoolV2",
    iconName: "curve",
    nameSubtitle: "avax.curve.fi",
    contractChain: 43114,
    id: 3,
    poolId: 0,
    stakingTokenType: "LP",
    stakingTokenName: "3PoolV2",
    stakingTokenIcon: "curve",
    stakingTokenLink: "https://avax.curve.fi/factory/4/deposit",
    stakingTokenAbi: [
      {
        name: "Transfer",
        inputs: [
          { type: "address", name: "sender", indexed: true },
          { type: "address", name: "receiver", indexed: true },
          { type: "uint256", name: "value", indexed: false },
        ],
        anonymous: false,
        type: "event",
      },
      {
        name: "Approval",
        inputs: [
          { type: "address", name: "owner", indexed: true },
          { type: "address", name: "spender", indexed: true },
          { type: "uint256", name: "value", indexed: false },
        ],
        anonymous: false,
        type: "event",
      },
      {
        name: "TokenExchange",
        inputs: [
          { type: "address", name: "buyer", indexed: true },
          { type: "int128", name: "sold_id", indexed: false },
          { type: "uint256", name: "tokens_sold", indexed: false },
          { type: "int128", name: "bought_id", indexed: false },
          { type: "uint256", name: "tokens_bought", indexed: false },
        ],
        anonymous: false,
        type: "event",
      },
      {
        name: "TokenExchangeUnderlying",
        inputs: [
          { type: "address", name: "buyer", indexed: true },
          { type: "int128", name: "sold_id", indexed: false },
          { type: "uint256", name: "tokens_sold", indexed: false },
          { type: "int128", name: "bought_id", indexed: false },
          { type: "uint256", name: "tokens_bought", indexed: false },
        ],
        anonymous: false,
        type: "event",
      },
      {
        name: "AddLiquidity",
        inputs: [
          { type: "address", name: "provider", indexed: true },
          { type: "uint256[2]", name: "token_amounts", indexed: false },
          { type: "uint256[2]", name: "fees", indexed: false },
          { type: "uint256", name: "invariant", indexed: false },
          { type: "uint256", name: "token_supply", indexed: false },
        ],
        anonymous: false,
        type: "event",
      },
      {
        name: "RemoveLiquidity",
        inputs: [
          { type: "address", name: "provider", indexed: true },
          { type: "uint256[2]", name: "token_amounts", indexed: false },
          { type: "uint256[2]", name: "fees", indexed: false },
          { type: "uint256", name: "token_supply", indexed: false },
        ],
        anonymous: false,
        type: "event",
      },
      {
        name: "RemoveLiquidityOne",
        inputs: [
          { type: "address", name: "provider", indexed: true },
          { type: "uint256", name: "token_amount", indexed: false },
          { type: "uint256", name: "coin_amount", indexed: false },
          { type: "uint256", name: "token_supply", indexed: false },
        ],
        anonymous: false,
        type: "event",
      },
      {
        name: "RemoveLiquidityImbalance",
        inputs: [
          { type: "address", name: "provider", indexed: true },
          { type: "uint256[2]", name: "token_amounts", indexed: false },
          { type: "uint256[2]", name: "fees", indexed: false },
          { type: "uint256", name: "invariant", indexed: false },
          { type: "uint256", name: "token_supply", indexed: false },
        ],
        anonymous: false,
        type: "event",
      },
      {
        name: "CommitNewAdmin",
        inputs: [
          { type: "uint256", name: "deadline", indexed: true },
          { type: "address", name: "admin", indexed: true },
        ],
        anonymous: false,
        type: "event",
      },
      {
        name: "NewAdmin",
        inputs: [{ type: "address", name: "admin", indexed: true }],
        anonymous: false,
        type: "event",
      },
      {
        name: "CommitNewFee",
        inputs: [
          { type: "uint256", name: "deadline", indexed: true },
          { type: "uint256", name: "fee", indexed: false },
          { type: "uint256", name: "admin_fee", indexed: false },
        ],
        anonymous: false,
        type: "event",
      },
      {
        name: "NewFee",
        inputs: [
          { type: "uint256", name: "fee", indexed: false },
          { type: "uint256", name: "admin_fee", indexed: false },
        ],
        anonymous: false,
        type: "event",
      },
      {
        name: "RampA",
        inputs: [
          { type: "uint256", name: "old_A", indexed: false },
          { type: "uint256", name: "new_A", indexed: false },
          { type: "uint256", name: "initial_time", indexed: false },
          { type: "uint256", name: "future_time", indexed: false },
        ],
        anonymous: false,
        type: "event",
      },
      {
        name: "StopRampA",
        inputs: [
          { type: "uint256", name: "A", indexed: false },
          { type: "uint256", name: "t", indexed: false },
        ],
        anonymous: false,
        type: "event",
      },
      {
        outputs: [],
        inputs: [],
        stateMutability: "nonpayable",
        type: "constructor",
      },
      {
        name: "initialize",
        outputs: [],
        inputs: [
          { type: "string", name: "_name" },
          { type: "string", name: "_symbol" },
          { type: "address", name: "_coin" },
          { type: "uint256", name: "_decimals" },
          { type: "uint256", name: "_A" },
          { type: "uint256", name: "_fee" },
          { type: "address", name: "_admin" },
        ],
        stateMutability: "nonpayable",
        type: "function",
        gas: 470049,
      },
      {
        name: "decimals",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [],
        stateMutability: "view",
        type: "function",
        gas: 291,
      },
      {
        name: "transfer",
        outputs: [{ type: "bool", name: "" }],
        inputs: [
          { type: "address", name: "_to" },
          { type: "uint256", name: "_value" },
        ],
        stateMutability: "nonpayable",
        type: "function",
        gas: 75402,
      },
      {
        name: "transferFrom",
        outputs: [{ type: "bool", name: "" }],
        inputs: [
          { type: "address", name: "_from" },
          { type: "address", name: "_to" },
          { type: "uint256", name: "_value" },
        ],
        stateMutability: "nonpayable",
        type: "function",
        gas: 112037,
      },
      {
        name: "approve",
        outputs: [{ type: "bool", name: "" }],
        inputs: [
          { type: "address", name: "_spender" },
          { type: "uint256", name: "_value" },
        ],
        stateMutability: "nonpayable",
        type: "function",
        gas: 37854,
      },
      {
        name: "get_previous_balances",
        outputs: [{ type: "uint256[2]", name: "" }],
        inputs: [],
        stateMutability: "view",
        type: "function",
        gas: 2254,
      },
      {
        name: "get_balances",
        outputs: [{ type: "uint256[2]", name: "" }],
        inputs: [],
        stateMutability: "view",
        type: "function",
        gas: 2284,
      },
      {
        name: "get_twap_balances",
        outputs: [{ type: "uint256[2]", name: "" }],
        inputs: [
          { type: "uint256[2]", name: "_first_balances" },
          { type: "uint256[2]", name: "_last_balances" },
          { type: "uint256", name: "_time_elapsed" },
        ],
        stateMutability: "view",
        type: "function",
        gas: 1522,
      },
      {
        name: "get_price_cumulative_last",
        outputs: [{ type: "uint256[2]", name: "" }],
        inputs: [],
        stateMutability: "view",
        type: "function",
        gas: 2344,
      },
      {
        name: "admin_fee",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [],
        stateMutability: "view",
        type: "function",
        gas: 621,
      },
      {
        name: "A",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [],
        stateMutability: "view",
        type: "function",
        gas: 5859,
      },
      {
        name: "A_precise",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [],
        stateMutability: "view",
        type: "function",
        gas: 5821,
      },
      {
        name: "get_virtual_price",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [],
        stateMutability: "view",
        type: "function",
        gas: 1011891,
      },
      {
        name: "calc_token_amount",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [
          { type: "uint256[2]", name: "_amounts" },
          { type: "bool", name: "_is_deposit" },
        ],
        stateMutability: "view",
        type: "function",
      },
      {
        name: "calc_token_amount",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [
          { type: "uint256[2]", name: "_amounts" },
          { type: "bool", name: "_is_deposit" },
          { type: "bool", name: "_previous" },
        ],
        stateMutability: "view",
        type: "function",
      },
      {
        name: "add_liquidity",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [
          { type: "uint256[2]", name: "_amounts" },
          { type: "uint256", name: "_min_mint_amount" },
        ],
        stateMutability: "nonpayable",
        type: "function",
      },
      {
        name: "add_liquidity",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [
          { type: "uint256[2]", name: "_amounts" },
          { type: "uint256", name: "_min_mint_amount" },
          { type: "address", name: "_receiver" },
        ],
        stateMutability: "nonpayable",
        type: "function",
      },
      {
        name: "get_dy",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [
          { type: "int128", name: "i" },
          { type: "int128", name: "j" },
          { type: "uint256", name: "dx" },
        ],
        stateMutability: "view",
        type: "function",
      },
      {
        name: "get_dy",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [
          { type: "int128", name: "i" },
          { type: "int128", name: "j" },
          { type: "uint256", name: "dx" },
          { type: "uint256[2]", name: "_balances" },
        ],
        stateMutability: "view",
        type: "function",
      },
      {
        name: "get_dy_underlying",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [
          { type: "int128", name: "i" },
          { type: "int128", name: "j" },
          { type: "uint256", name: "dx" },
        ],
        stateMutability: "view",
        type: "function",
      },
      {
        name: "get_dy_underlying",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [
          { type: "int128", name: "i" },
          { type: "int128", name: "j" },
          { type: "uint256", name: "dx" },
          { type: "uint256[2]", name: "_balances" },
        ],
        stateMutability: "view",
        type: "function",
      },
      {
        name: "exchange",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [
          { type: "int128", name: "i" },
          { type: "int128", name: "j" },
          { type: "uint256", name: "dx" },
          { type: "uint256", name: "min_dy" },
        ],
        stateMutability: "nonpayable",
        type: "function",
      },
      {
        name: "exchange",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [
          { type: "int128", name: "i" },
          { type: "int128", name: "j" },
          { type: "uint256", name: "dx" },
          { type: "uint256", name: "min_dy" },
          { type: "address", name: "_receiver" },
        ],
        stateMutability: "nonpayable",
        type: "function",
      },
      {
        name: "exchange_underlying",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [
          { type: "int128", name: "i" },
          { type: "int128", name: "j" },
          { type: "uint256", name: "dx" },
          { type: "uint256", name: "min_dy" },
        ],
        stateMutability: "nonpayable",
        type: "function",
      },
      {
        name: "exchange_underlying",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [
          { type: "int128", name: "i" },
          { type: "int128", name: "j" },
          { type: "uint256", name: "dx" },
          { type: "uint256", name: "min_dy" },
          { type: "address", name: "_receiver" },
        ],
        stateMutability: "nonpayable",
        type: "function",
      },
      {
        name: "remove_liquidity",
        outputs: [{ type: "uint256[2]", name: "" }],
        inputs: [
          { type: "uint256", name: "_burn_amount" },
          { type: "uint256[2]", name: "_min_amounts" },
        ],
        stateMutability: "nonpayable",
        type: "function",
      },
      {
        name: "remove_liquidity",
        outputs: [{ type: "uint256[2]", name: "" }],
        inputs: [
          { type: "uint256", name: "_burn_amount" },
          { type: "uint256[2]", name: "_min_amounts" },
          { type: "address", name: "_receiver" },
        ],
        stateMutability: "nonpayable",
        type: "function",
      },
      {
        name: "remove_liquidity_imbalance",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [
          { type: "uint256[2]", name: "_amounts" },
          { type: "uint256", name: "_max_burn_amount" },
        ],
        stateMutability: "nonpayable",
        type: "function",
      },
      {
        name: "remove_liquidity_imbalance",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [
          { type: "uint256[2]", name: "_amounts" },
          { type: "uint256", name: "_max_burn_amount" },
          { type: "address", name: "_receiver" },
        ],
        stateMutability: "nonpayable",
        type: "function",
      },
      {
        name: "calc_withdraw_one_coin",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [
          { type: "uint256", name: "_burn_amount" },
          { type: "int128", name: "i" },
        ],
        stateMutability: "view",
        type: "function",
      },
      {
        name: "calc_withdraw_one_coin",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [
          { type: "uint256", name: "_burn_amount" },
          { type: "int128", name: "i" },
          { type: "bool", name: "_previous" },
        ],
        stateMutability: "view",
        type: "function",
      },
      {
        name: "remove_liquidity_one_coin",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [
          { type: "uint256", name: "_burn_amount" },
          { type: "int128", name: "i" },
          { type: "uint256", name: "_min_received" },
        ],
        stateMutability: "nonpayable",
        type: "function",
      },
      {
        name: "remove_liquidity_one_coin",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [
          { type: "uint256", name: "_burn_amount" },
          { type: "int128", name: "i" },
          { type: "uint256", name: "_min_received" },
          { type: "address", name: "_receiver" },
        ],
        stateMutability: "nonpayable",
        type: "function",
      },
      {
        name: "ramp_A",
        outputs: [],
        inputs: [
          { type: "uint256", name: "_future_A" },
          { type: "uint256", name: "_future_time" },
        ],
        stateMutability: "nonpayable",
        type: "function",
        gas: 152464,
      },
      {
        name: "stop_ramp_A",
        outputs: [],
        inputs: [],
        stateMutability: "nonpayable",
        type: "function",
        gas: 149225,
      },
      {
        name: "admin_balances",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [{ type: "uint256", name: "i" }],
        stateMutability: "view",
        type: "function",
        gas: 3601,
      },
      {
        name: "withdraw_admin_fees",
        outputs: [],
        inputs: [],
        stateMutability: "nonpayable",
        type: "function",
        gas: 11347,
      },
      {
        name: "admin",
        outputs: [{ type: "address", name: "" }],
        inputs: [],
        stateMutability: "view",
        type: "function",
        gas: 2141,
      },
      {
        name: "coins",
        outputs: [{ type: "address", name: "" }],
        inputs: [{ type: "uint256", name: "arg0" }],
        stateMutability: "view",
        type: "function",
        gas: 2280,
      },
      {
        name: "balances",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [{ type: "uint256", name: "arg0" }],
        stateMutability: "view",
        type: "function",
        gas: 2310,
      },
      {
        name: "fee",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [],
        stateMutability: "view",
        type: "function",
        gas: 2231,
      },
      {
        name: "block_timestamp_last",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [],
        stateMutability: "view",
        type: "function",
        gas: 2261,
      },
      {
        name: "initial_A",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [],
        stateMutability: "view",
        type: "function",
        gas: 2291,
      },
      {
        name: "future_A",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [],
        stateMutability: "view",
        type: "function",
        gas: 2321,
      },
      {
        name: "initial_A_time",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [],
        stateMutability: "view",
        type: "function",
        gas: 2351,
      },
      {
        name: "future_A_time",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [],
        stateMutability: "view",
        type: "function",
        gas: 2381,
      },
      {
        name: "name",
        outputs: [{ type: "string", name: "" }],
        inputs: [],
        stateMutability: "view",
        type: "function",
        gas: 8813,
      },
      {
        name: "symbol",
        outputs: [{ type: "string", name: "" }],
        inputs: [],
        stateMutability: "view",
        type: "function",
        gas: 7866,
      },
      {
        name: "balanceOf",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [{ type: "address", name: "arg0" }],
        stateMutability: "view",
        type: "function",
        gas: 2686,
      },
      {
        name: "allowance",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [
          { type: "address", name: "arg0" },
          { type: "address", name: "arg1" },
        ],
        stateMutability: "view",
        type: "function",
        gas: 2931,
      },
      {
        name: "totalSupply",
        outputs: [{ type: "uint256", name: "" }],
        inputs: [],
        stateMutability: "view",
        type: "function",
        gas: 2531,
      },
    ],
    contract: {
      name: "Sorbettiere",
      address: "0x06408571E0aD5e8F52eAd01450Bde74E5074dC74",
      abi: [
        {
          inputs: [
            { internalType: "contract IERC20", name: "_ice", type: "address" },
            { internalType: "uint256", name: "_icePerSecond", type: "uint256" },
            { internalType: "uint32", name: "_startTime", type: "uint32" },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "pid",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "Deposit",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "pid",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "EmergencyWithdraw",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "pid",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "Withdraw",
          type: "event",
        },
        {
          inputs: [
            { internalType: "uint16", name: "_allocPoint", type: "uint16" },
            {
              internalType: "contract IERC20",
              name: "_stakingToken",
              type: "address",
            },
            { internalType: "bool", name: "_withUpdate", type: "bool" },
          ],
          name: "add",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "uint32", name: "addSeconds", type: "uint32" },
          ],
          name: "changeEndTime",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "claimOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "uint256", name: "_pid", type: "uint256" },
            { internalType: "uint256", name: "_amount", type: "uint256" },
          ],
          name: "deposit",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ internalType: "uint256", name: "_pid", type: "uint256" }],
          name: "emergencyWithdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "endTime",
          outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "uint256", name: "_from", type: "uint256" },
            { internalType: "uint256", name: "_to", type: "uint256" },
          ],
          name: "getMultiplier",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "ice",
          outputs: [
            { internalType: "contract IERC20", name: "", type: "address" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "icePerSecond",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "massUpdatePools",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [{ internalType: "address", name: "", type: "address" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "uint256", name: "_pid", type: "uint256" },
            { internalType: "address", name: "_user", type: "address" },
          ],
          name: "pendingIce",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "pendingOwner",
          outputs: [{ internalType: "address", name: "", type: "address" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          name: "poolInfo",
          outputs: [
            {
              internalType: "contract IERC20",
              name: "stakingToken",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "stakingTokenTotalAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "accIcePerShare",
              type: "uint256",
            },
            { internalType: "uint32", name: "lastRewardTime", type: "uint32" },
            { internalType: "uint16", name: "allocPoint", type: "uint16" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "poolLength",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "uint256", name: "_pid", type: "uint256" },
            { internalType: "uint16", name: "_allocPoint", type: "uint16" },
            { internalType: "bool", name: "_withUpdate", type: "bool" },
          ],
          name: "set",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "uint256", name: "_icePerSecond", type: "uint256" },
            { internalType: "bool", name: "_withUpdate", type: "bool" },
          ],
          name: "setIcePerSecond",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "startTime",
          outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalAllocPoint",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "newOwner", type: "address" },
            { internalType: "bool", name: "direct", type: "bool" },
            { internalType: "bool", name: "renounce", type: "bool" },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ internalType: "uint256", name: "_pid", type: "uint256" }],
          name: "updatePool",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "uint256", name: "", type: "uint256" },
            { internalType: "address", name: "", type: "address" },
          ],
          name: "userInfo",
          outputs: [
            { internalType: "uint256", name: "amount", type: "uint256" },
            { internalType: "uint256", name: "rewardDebt", type: "uint256" },
            {
              internalType: "uint256",
              name: "remainingIceTokenReward",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "uint256", name: "_pid", type: "uint256" },
            { internalType: "uint256", name: "_amount", type: "uint256" },
          ],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
    },
    token: {
      name: "Spell",
      tokenIdx: 0,
      decimals: 18,
      address: "0xCE1bFFBD5374Dac86a2893119683F4911a2F7814",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "_owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "_spender",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "_value",
              type: "uint256",
            },
          ],
          name: "Approval",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "_from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "_to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "_value",
              type: "uint256",
            },
          ],
          name: "Transfer",
          type: "event",
        },
        {
          inputs: [],
          name: "DOMAIN_SEPARATOR",
          outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "", type: "address" },
            { internalType: "address", name: "", type: "address" },
          ],
          name: "allowance",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "spender", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
          ],
          name: "approve",
          outputs: [{ internalType: "bool", name: "", type: "bool" }],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "", type: "address" }],
          name: "balanceOf",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "uint256", name: "amount", type: "uint256" },
          ],
          name: "burn",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "claimOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "decimals",
          outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "lastMint",
          outputs: [
            { internalType: "uint128", name: "time", type: "uint128" },
            { internalType: "uint128", name: "amount", type: "uint128" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "to", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
          ],
          name: "mint",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "clone", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
            {
              internalType: "contract IBentoBoxV1",
              name: "bentoBox",
              type: "address",
            },
          ],
          name: "mintToBentoBox",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "name",
          outputs: [{ internalType: "string", name: "", type: "string" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "", type: "address" }],
          name: "nonces",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [{ internalType: "address", name: "", type: "address" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "pendingOwner",
          outputs: [{ internalType: "address", name: "", type: "address" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "owner_", type: "address" },
            { internalType: "address", name: "spender", type: "address" },
            { internalType: "uint256", name: "value", type: "uint256" },
            { internalType: "uint256", name: "deadline", type: "uint256" },
            { internalType: "uint8", name: "v", type: "uint8" },
            { internalType: "bytes32", name: "r", type: "bytes32" },
            { internalType: "bytes32", name: "s", type: "bytes32" },
          ],
          name: "permit",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "symbol",
          outputs: [{ internalType: "string", name: "", type: "string" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalSupply",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "to", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
          ],
          name: "transfer",
          outputs: [{ internalType: "bool", name: "", type: "bool" }],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "from", type: "address" },
            { internalType: "address", name: "to", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
          ],
          name: "transferFrom",
          outputs: [{ internalType: "bool", name: "", type: "bool" }],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "newOwner", type: "address" },
            { internalType: "bool", name: "direct", type: "bool" },
            { internalType: "bool", name: "renounce", type: "bool" },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
    },
    erc20Abi: [
      { inputs: [], stateMutability: "nonpayable", type: "constructor" },
      {
        anonymous: false,
        inputs: [
          {
            indexed: true,
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            indexed: true,
            internalType: "address",
            name: "spender",
            type: "address",
          },
          {
            indexed: false,
            internalType: "uint256",
            name: "value",
            type: "uint256",
          },
        ],
        name: "Approval",
        type: "event",
      },
      {
        anonymous: false,
        inputs: [
          {
            indexed: true,
            internalType: "address",
            name: "sender",
            type: "address",
          },
          {
            indexed: false,
            internalType: "uint256",
            name: "amount0",
            type: "uint256",
          },
          {
            indexed: false,
            internalType: "uint256",
            name: "amount1",
            type: "uint256",
          },
          {
            indexed: true,
            internalType: "address",
            name: "to",
            type: "address",
          },
        ],
        name: "Burn",
        type: "event",
      },
      {
        anonymous: false,
        inputs: [
          {
            indexed: true,
            internalType: "address",
            name: "sender",
            type: "address",
          },
          {
            indexed: false,
            internalType: "uint256",
            name: "amount0",
            type: "uint256",
          },
          {
            indexed: false,
            internalType: "uint256",
            name: "amount1",
            type: "uint256",
          },
        ],
        name: "Mint",
        type: "event",
      },
      {
        anonymous: false,
        inputs: [
          {
            indexed: true,
            internalType: "address",
            name: "sender",
            type: "address",
          },
          {
            indexed: false,
            internalType: "uint256",
            name: "amount0In",
            type: "uint256",
          },
          {
            indexed: false,
            internalType: "uint256",
            name: "amount1In",
            type: "uint256",
          },
          {
            indexed: false,
            internalType: "uint256",
            name: "amount0Out",
            type: "uint256",
          },
          {
            indexed: false,
            internalType: "uint256",
            name: "amount1Out",
            type: "uint256",
          },
          {
            indexed: true,
            internalType: "address",
            name: "to",
            type: "address",
          },
        ],
        name: "Swap",
        type: "event",
      },
      {
        anonymous: false,
        inputs: [
          {
            indexed: false,
            internalType: "uint112",
            name: "reserve0",
            type: "uint112",
          },
          {
            indexed: false,
            internalType: "uint112",
            name: "reserve1",
            type: "uint112",
          },
        ],
        name: "Sync",
        type: "event",
      },
      {
        anonymous: false,
        inputs: [
          {
            indexed: true,
            internalType: "address",
            name: "from",
            type: "address",
          },
          {
            indexed: true,
            internalType: "address",
            name: "to",
            type: "address",
          },
          {
            indexed: false,
            internalType: "uint256",
            name: "value",
            type: "uint256",
          },
        ],
        name: "Transfer",
        type: "event",
      },
      {
        inputs: [],
        name: "DOMAIN_SEPARATOR",
        outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
        stateMutability: "view",
        type: "function",
      },
      {
        inputs: [],
        name: "MINIMUM_LIQUIDITY",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
      },
      {
        inputs: [],
        name: "PERMIT_TYPEHASH",
        outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
        stateMutability: "view",
        type: "function",
      },
      {
        inputs: [
          { internalType: "address", name: "", type: "address" },
          { internalType: "address", name: "", type: "address" },
        ],
        name: "allowance",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
      },
      {
        inputs: [
          { internalType: "address", name: "spender", type: "address" },
          { internalType: "uint256", name: "value", type: "uint256" },
        ],
        name: "approve",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        stateMutability: "nonpayable",
        type: "function",
      },
      {
        inputs: [{ internalType: "address", name: "", type: "address" }],
        name: "balanceOf",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
      },
      {
        inputs: [{ internalType: "address", name: "to", type: "address" }],
        name: "burn",
        outputs: [
          { internalType: "uint256", name: "amount0", type: "uint256" },
          { internalType: "uint256", name: "amount1", type: "uint256" },
        ],
        stateMutability: "nonpayable",
        type: "function",
      },
      {
        inputs: [],
        name: "decimals",
        outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
        stateMutability: "view",
        type: "function",
      },
      {
        inputs: [],
        name: "factory",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
      },
      {
        inputs: [],
        name: "getReserves",
        outputs: [
          { internalType: "uint112", name: "_reserve0", type: "uint112" },
          { internalType: "uint112", name: "_reserve1", type: "uint112" },
          {
            internalType: "uint32",
            name: "_blockTimestampLast",
            type: "uint32",
          },
        ],
        stateMutability: "view",
        type: "function",
      },
      {
        inputs: [
          { internalType: "address", name: "_token0", type: "address" },
          { internalType: "address", name: "_token1", type: "address" },
        ],
        name: "initialize",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
      },
      {
        inputs: [],
        name: "kLast",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
      },
      {
        inputs: [{ internalType: "address", name: "to", type: "address" }],
        name: "mint",
        outputs: [
          { internalType: "uint256", name: "liquidity", type: "uint256" },
        ],
        stateMutability: "nonpayable",
        type: "function",
      },
      {
        inputs: [],
        name: "name",
        outputs: [{ internalType: "string", name: "", type: "string" }],
        stateMutability: "view",
        type: "function",
      },
      {
        inputs: [{ internalType: "address", name: "", type: "address" }],
        name: "nonces",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
      },
      {
        inputs: [
          { internalType: "address", name: "owner", type: "address" },
          { internalType: "address", name: "spender", type: "address" },
          { internalType: "uint256", name: "value", type: "uint256" },
          { internalType: "uint256", name: "deadline", type: "uint256" },
          { internalType: "uint8", name: "v", type: "uint8" },
          { internalType: "bytes32", name: "r", type: "bytes32" },
          { internalType: "bytes32", name: "s", type: "bytes32" },
        ],
        name: "permit",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
      },
      {
        inputs: [],
        name: "price0CumulativeLast",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
      },
      {
        inputs: [],
        name: "price1CumulativeLast",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
      },
      {
        inputs: [{ internalType: "address", name: "to", type: "address" }],
        name: "skim",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
      },
      {
        inputs: [
          { internalType: "uint256", name: "amount0Out", type: "uint256" },
          { internalType: "uint256", name: "amount1Out", type: "uint256" },
          { internalType: "address", name: "to", type: "address" },
          { internalType: "bytes", name: "data", type: "bytes" },
        ],
        name: "swap",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
      },
      {
        inputs: [],
        name: "symbol",
        outputs: [{ internalType: "string", name: "", type: "string" }],
        stateMutability: "view",
        type: "function",
      },
      {
        inputs: [],
        name: "sync",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
      },
      {
        inputs: [],
        name: "token0",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
      },
      {
        inputs: [],
        name: "token1",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
      },
      {
        inputs: [],
        name: "totalSupply",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
      },
      {
        inputs: [
          { internalType: "address", name: "to", type: "address" },
          { internalType: "uint256", name: "value", type: "uint256" },
        ],
        name: "transfer",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        stateMutability: "nonpayable",
        type: "function",
      },
      {
        inputs: [
          { internalType: "address", name: "from", type: "address" },
          { internalType: "address", name: "to", type: "address" },
          { internalType: "uint256", name: "value", type: "uint256" },
        ],
        name: "transferFrom",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        stateMutability: "nonpayable",
        type: "function",
      },
    ],
  },
];
