export default [
  {
    type: "constructor",
    stateMutability: "nonpayable",
    inputs: [
      { type: "address", name: "_vault", internalType: "address" },
      { type: "address", name: "_usdk", internalType: "address" },
      { type: "address", name: "_klp", internalType: "address" },
      { type: "address", name: "_shortsTracker", internalType: "address" },
      { type: "uint256", name: "_cooldownDuration", internalType: "uint256" },
    ],
  },
  {
    type: "event",
    name: "AddLiquidity",
    inputs: [
      {
        type: "address",
        name: "account",
        internalType: "address",
        indexed: false,
      },
      {
        type: "address",
        name: "token",
        internalType: "address",
        indexed: false,
      },
      {
        type: "uint256",
        name: "amount",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "aumInUsdk",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "klpSupply",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "usdkAmount",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "mintAmount",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RemoveLiquidity",
    inputs: [
      {
        type: "address",
        name: "account",
        internalType: "address",
        indexed: false,
      },
      {
        type: "address",
        name: "token",
        internalType: "address",
        indexed: false,
      },
      {
        type: "uint256",
        name: "klpAmount",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "aumInUsdk",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "klpSupply",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "usdkAmount",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "amountOut",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "BASIS_POINTS_DIVISOR",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "KLP_PRECISION",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "MAX_COOLDOWN_DURATION",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "PRICE_PRECISION",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "USDK_DECIMALS",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "addLiquidity",
    inputs: [
      { type: "address", name: "_token", internalType: "address" },
      { type: "uint256", name: "_amount", internalType: "uint256" },
      { type: "uint256", name: "_minUsdk", internalType: "uint256" },
      { type: "uint256", name: "_minKlp", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "addLiquidityForAccount",
    inputs: [
      { type: "address", name: "_fundingAccount", internalType: "address" },
      { type: "address", name: "_account", internalType: "address" },
      { type: "address", name: "_token", internalType: "address" },
      { type: "uint256", name: "_amount", internalType: "uint256" },
      { type: "uint256", name: "_minUsdk", internalType: "uint256" },
      { type: "uint256", name: "_minKlp", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "aumAddition",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "aumDeduction",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "cooldownDuration",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "getAum",
    inputs: [{ type: "bool", name: "maximise", internalType: "bool" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "getAumInUsdk",
    inputs: [{ type: "bool", name: "maximise", internalType: "bool" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
    name: "getAums",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "getGlobalShortAveragePrice",
    inputs: [{ type: "address", name: "_token", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "uint256", name: "", internalType: "uint256" },
      { type: "bool", name: "", internalType: "bool" },
    ],
    name: "getGlobalShortDelta",
    inputs: [
      { type: "address", name: "_token", internalType: "address" },
      { type: "uint256", name: "_price", internalType: "uint256" },
      { type: "uint256", name: "_size", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "getPrice",
    inputs: [{ type: "bool", name: "_maximise", internalType: "bool" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "gov",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "inPrivateMode",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "isHandler",
    inputs: [{ type: "address", name: "", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "klp",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "lastAddedAt",
    inputs: [{ type: "address", name: "", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "removeLiquidity",
    inputs: [
      { type: "address", name: "_tokenOut", internalType: "address" },
      { type: "uint256", name: "_klpAmount", internalType: "uint256" },
      { type: "uint256", name: "_minOut", internalType: "uint256" },
      { type: "address", name: "_receiver", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "removeLiquidityForAccount",
    inputs: [
      { type: "address", name: "_account", internalType: "address" },
      { type: "address", name: "_tokenOut", internalType: "address" },
      { type: "uint256", name: "_klpAmount", internalType: "uint256" },
      { type: "uint256", name: "_minOut", internalType: "uint256" },
      { type: "address", name: "_receiver", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setAumAdjustment",
    inputs: [
      { type: "uint256", name: "_aumAddition", internalType: "uint256" },
      { type: "uint256", name: "_aumDeduction", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setCooldownDuration",
    inputs: [
      { type: "uint256", name: "_cooldownDuration", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setGov",
    inputs: [{ type: "address", name: "_gov", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setHandler",
    inputs: [
      { type: "address", name: "_handler", internalType: "address" },
      { type: "bool", name: "_isActive", internalType: "bool" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setInPrivateMode",
    inputs: [{ type: "bool", name: "_inPrivateMode", internalType: "bool" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setShortsTracker",
    inputs: [
      {
        type: "address",
        name: "_shortsTracker",
        internalType: "contract IShortsTracker",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setShortsTrackerAveragePriceWeight",
    inputs: [
      {
        type: "uint256",
        name: "_shortsTrackerAveragePriceWeight",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "address", name: "", internalType: "contract IShortsTracker" },
    ],
    name: "shortsTracker",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "shortsTrackerAveragePriceWeight",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "usdk",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "contract IVault" }],
    name: "vault",
    inputs: [],
  },
];
