export default [
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "BASIS_POINTS_DIVISOR",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "POSITION_PROPS_LENGTH",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "PRICE_PRECISION",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "USDK_DECIMALS",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "uint256", name: "", internalType: "uint256" },
      { type: "uint256", name: "", internalType: "uint256" },
    ],
    name: "getAmountOut",
    inputs: [
      { type: "address", name: "_vault", internalType: "contract IVault" },
      { type: "address", name: "_tokenIn", internalType: "address" },
      { type: "address", name: "_tokenOut", internalType: "address" },
      { type: "uint256", name: "_amountIn", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "uint256", name: "", internalType: "uint256" },
      { type: "uint256", name: "", internalType: "uint256" },
      { type: "uint256", name: "", internalType: "uint256" },
    ],
    name: "getFeeBasisPoints",
    inputs: [
      { type: "address", name: "_vault", internalType: "contract IVault" },
      { type: "address", name: "_tokenIn", internalType: "address" },
      { type: "address", name: "_tokenOut", internalType: "address" },
      { type: "uint256", name: "_amountIn", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
    name: "getFees",
    inputs: [
      { type: "address", name: "_vault", internalType: "address" },
      { type: "address[]", name: "_tokens", internalType: "address[]" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
    name: "getFullVaultTokenInfo",
    inputs: [
      { type: "address", name: "_vault", internalType: "address" },
      { type: "address", name: "_weth", internalType: "address" },
      { type: "uint256", name: "_usdkAmount", internalType: "uint256" },
      { type: "address[]", name: "_tokens", internalType: "address[]" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
    name: "getFundingRates",
    inputs: [
      { type: "address", name: "_vault", internalType: "address" },
      { type: "address", name: "_weth", internalType: "address" },
      { type: "address[]", name: "_tokens", internalType: "address[]" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "getMaxAmountIn",
    inputs: [
      { type: "address", name: "_vault", internalType: "contract IVault" },
      { type: "address", name: "_tokenIn", internalType: "address" },
      { type: "address", name: "_tokenOut", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
    name: "getPositions",
    inputs: [
      { type: "address", name: "_vault", internalType: "address" },
      { type: "address", name: "_account", internalType: "address" },
      {
        type: "address[]",
        name: "_collateralTokens",
        internalType: "address[]",
      },
      { type: "address[]", name: "_indexTokens", internalType: "address[]" },
      { type: "bool[]", name: "_isLong", internalType: "bool[]" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
    name: "getPrices",
    inputs: [
      {
        type: "address",
        name: "_priceFeed",
        internalType: "contract IVaultPriceFeed",
      },
      { type: "address[]", name: "_tokens", internalType: "address[]" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
    name: "getTokenBalances",
    inputs: [
      { type: "address", name: "_account", internalType: "address" },
      { type: "address[]", name: "_tokens", internalType: "address[]" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
    name: "getTokenBalancesWithSupplies",
    inputs: [
      { type: "address", name: "_account", internalType: "address" },
      { type: "address[]", name: "_tokens", internalType: "address[]" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "getTokenSupply",
    inputs: [
      { type: "address", name: "_token", internalType: "contract IERC20" },
      {
        type: "address[]",
        name: "_excludedAccounts",
        internalType: "address[]",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "getTotalBalance",
    inputs: [
      { type: "address", name: "_token", internalType: "contract IERC20" },
      { type: "address[]", name: "_accounts", internalType: "address[]" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
    name: "getTotalStaked",
    inputs: [
      { type: "address[]", name: "_yieldTokens", internalType: "address[]" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
    name: "getVaultTokenInfo",
    inputs: [
      { type: "address", name: "_vault", internalType: "address" },
      { type: "address", name: "_weth", internalType: "address" },
      { type: "uint256", name: "_usdkAmount", internalType: "uint256" },
      { type: "address[]", name: "_tokens", internalType: "address[]" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
    name: "getVaultTokenInfoV2",
    inputs: [
      { type: "address", name: "_vault", internalType: "address" },
      { type: "address", name: "_weth", internalType: "address" },
      { type: "uint256", name: "_usdkAmount", internalType: "uint256" },
      { type: "address[]", name: "_tokens", internalType: "address[]" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "gov",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "hasMaxGlobalShortSizes",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setConfig",
    inputs: [
      { type: "bool", name: "_hasMaxGlobalShortSizes", internalType: "bool" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setGov",
    inputs: [{ type: "address", name: "_gov", internalType: "address" }],
  },
];
