export default [
  {
    type: "constructor",
    stateMutability: "nonpayable",
    inputs: [
      {
        type: "address",
        name: "_bentoBox",
        internalType: "contract IBentoBoxV1",
      },
      { type: "address", name: "_vault", internalType: "contract IERC4626" },
      { type: "address", name: "_mim", internalType: "contract IERC20" },
      {
        type: "uint8",
        name: "_curvePoolInterfaceType",
        internalType: "enum CurvePoolInterfaceType",
      },
      { type: "address", name: "_curvePool", internalType: "address" },
      { type: "address", name: "_curvePoolDepositor", internalType: "address" },
      {
        type: "address[]",
        name: "_poolTokens",
        internalType: "contract IERC20[]",
      },
      { type: "address", name: "_exchange", internalType: "address" },
    ],
  },
  { type: "error", name: "ErrApproveFailed", inputs: [] },
  {
    type: "error",
    name: "ErrApproveFailedWithData",
    inputs: [{ type: "bytes", name: "data", internalType: "bytes" }],
  },
  { type: "error", name: "ErrSwapFailed", inputs: [] },
  { type: "error", name: "ErrUnsupportedCurvePool", inputs: [] },
  { type: "error", name: "ErrUnsupportedCurvePoolLength", inputs: [] },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "address", name: "", internalType: "contract IBentoBoxV1" },
    ],
    name: "bentoBox",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "curvePool",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "curvePoolCoinsLength",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "curvePoolDepositor",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "uint8", name: "", internalType: "enum CurvePoolInterfaceType" },
    ],
    name: "curvePoolInterfaceType",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "contract IERC20" }],
    name: "curveToken",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "contract IERC20" }],
    name: "mim",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [
      { type: "uint256", name: "extraShare", internalType: "uint256" },
      { type: "uint256", name: "shareReturned", internalType: "uint256" },
    ],
    name: "swap",
    inputs: [
      { type: "address", name: "recipient", internalType: "address" },
      { type: "uint256", name: "shareToMin", internalType: "uint256" },
      { type: "uint256", name: "shareFrom", internalType: "uint256" },
      { type: "bytes", name: "data", internalType: "bytes" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "contract IERC4626" }],
    name: "vault",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "zeroXExchangeProxy",
    inputs: [],
  },
];
